language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - php vendor/bin/codacycoverage clover coverage.xml

notifications:
  email: false
